platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'vertretungsplanApp' do
  # Pods for vertretungsplanApp
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!


  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'




  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'

  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-background-worker', :path => '../node_modules/react-native-background-worker'

  pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'

  pod 'react-native-get-random-values', :path => '../node_modules/react-native-get-random-values'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

end
